apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: jkuli-mch-integration-test
spec:
  params:
    - description: 'Snapshot of the application'
      name: SNAPSHOT
      default: |
        {
          "application": "release-acm-211",
          "components": [{
            "name": "config-policy-controller-acm-211",
            "containerImage": "quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/config-policy-controller-acm-211@sha256:4a28d4e8f2409815a9abc691408d6f75afbee04064ea2524d6c06f12e65ec93e",
            "source": {
              "git": {
                "url": "https://github.com/stolostron/config-policy-controller",
                "revision": "1082f5e293acc33c656ae8d136d76f4c0f7eef89"
              }
            }
          }],
          "artifacts": {}
        }
      type: string
  tasks:
    - name: provision-eaas-space
      # Based on https://github.com/konflux-ci/build-definitions/blob/21db0a06facdaf3cb5255e83bc9eeaead303465b/task/eaas-provision-space/0.1/eaas-provision-space.yaml
      # but using direct tekton variable substitutions because I live dangerously
      taskSpec:
        results:
          - name: secretRef
            description: Name of a Secret containing a kubeconfig used to access the provisioned space.
        steps:
          - image: registry.redhat.io/openshift4/ose-cli:latest
            script: |
              #!/usr/bin/env bash
              set -euo pipefail

              cat <<EOF > space_request.yaml
              apiVersion: toolchain.dev.openshift.com/v1alpha1
              kind: SpaceRequest
              metadata:
                generateName: eaas-spacerequest-
                namespace: "$(context.taskRun.namespace)"
                ownerReferences:
                - apiVersion: tekton.dev/v1
                  kind: PipelineRun
                  name: "$(context.pipelineRun.name)"
                  uid: "$(context.pipelineRun.uid)"
              spec:
                tierName: konflux-eaas
                targetClusterRoles:
                - cluster-role.toolchain.dev.openshift.com/eaas
              EOF

              cat space_request.yaml

              NAME=$(oc create -f space_request.yaml -o=jsonpath='{.metadata.name}')

              echo "Waiting for SpaceRequest ${NAME} to be ready"
              if oc wait spacerequests $NAME --for=condition=Ready --timeout=5m; then
                echo "Got secretRef"
                oc get spacerequests $NAME -o=jsonpath='{.status.namespaceAccess[0].secretRef}' | tee $(results.secretRef.path)
              else
                exit 1
              fi
    - name: provision-cluster
      # Based on https://github.com/konflux-ci/build-definitions/tree/21db0a06facdaf3cb5255e83bc9eeaead303465b/stepactions
      # but in one simpler step
      params:
        - name: OCP_VERSION_PREFIX
          value: '4.15.'
        - name: eaas-secretref
          value: $(tasks.provision-eaas-space.results.secretRef)
      taskSpec:
        params:
          - name: OCP_VERSION_PREFIX
          - name: eaas-secretref
        results:
          - name: clusterName
            description: The name of the generated ClusterTemplateInstance resource.
        volumes:
          - name: eaas-kubeconfig
            secret:
              secretName: $(params.eaas-secretref)
        steps:
          - image: registry.redhat.io/openshift4/ose-cli:latest
            env:
              - name: KUBECONFIG
                value: /tmp/eaas-kubeconfig/kubeconfig
            volumeMounts:
              - name: eaas-kubeconfig
                mountPath: /tmp/eaas-kubeconfig
            script: |
              #!/usr/bin/env bash
              set -euo pipefail

              dnf -y install jq

              URL="https://amd64.ocp.releases.ci.openshift.org/api/v1/releasestream/4-stable/latest?prefix=$(params.OCP_VERSION_PREFIX)"
              VERSION=$(curl -f -s -L -H "Accepts: application/json" "${URL}" | jq -j '.name')

              cat <<EOF > cti.yaml
              apiVersion: clustertemplate.openshift.io/v1alpha1
              kind: ClusterTemplateInstance
              metadata:
                generateName: cluster-
              spec:
                clusterTemplateRef: hypershift-aws-cluster
                parameters:
                  - name: instanceType
                    value: m6g.large
                  - name: version
                    value: ${VERSION}
                  - name: timeout
                    value: 30m
              EOF

              cat cti.yaml

              CTI_NAME=$(oc create -f cti.yaml -o=jsonpath='{.metadata.name}')

              echo "Waiting for ClusterTemplateInstance ${CTI_NAME} to be ready"
              if oc wait cti "${CTI_NAME}" --for=jsonpath='{.status.phase}'=Ready --timeout=30m; then
                echo "Successfully provisioned ${CTI_NAME}"
              else
                echo "Failed to provision ${CTI_NAME}"
                oc get cti "${CTI_NAME}" -o yaml
                exit 1
              fi

              echo -n "${CTI_NAME}" > $(results.clusterName.path)
    - name: bundle-deploy
      params:
        - name: clusterName
          value: $(tasks.provision-cluster.results.clusterName)
        - name: eaas-secretref
          value: $(tasks.provision-eaas-space.results.secretRef)
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
      taskSpec:
        params:
          - name: clusterName
          - name: eaas-secretref
          - name: SNAPSHOT
        volumes:
          - name: eaas-kubeconfig
            secret:
              secretName: $(params.eaas-secretref)
        steps:
          - image: registry.redhat.io/openshift4/ose-cli:latest
            volumeMounts:
              - name: eaas-kubeconfig
                mountPath: /tmp/eaas-kubeconfig
            env:
              - name: SNAPSHOT
                value: $(params.SNAPSHOT)
            script: |
              #!/usr/bin/env bash
              set -euo pipefail

              # We will switch to provisioned cluster kubeconfig later
              export KUBECONFIG=/tmp/eaas-kubeconfig/kubeconfig
              
              cti_name="$(tasks.provision-cluster.results.clusterName)"
              SECRET_NAME=$(oc get cti "${cti_name}" -o=jsonpath='{.status.kubeconfig.name}')
              mkdir -p /tmp/hyper-kubeconfig
              oc extract secret/${SECRET_NAME} --to=/tmp/hyper-kubeconfig

              export KUBECONFIG=/tmp/hyper-kubeconfig/kubeconfig

              echo "Cloning config-policy-controller repository"
              dnf -y install make git
              git clone https://github.com/stolostron/config-policy-controller.git
              cd config-policy-controller/

              cp /tmp/hyper-kubeconfig/kubeconfig ./kubeconfig_managed
              cp /tmp/hyper-kubeconfig/kubeconfig ./kubeconfig_managed_e2e

              oc apply -f https://raw.githubusercontent.com/open-cluster-management-io/governance-policy-propagator/main/deploy/crds/policy.open-cluster-management.io_policies.yaml
              oc apply -f deploy/crds/policy.open-cluster-management.io_configurationpolicies.yaml
              oc apply -f deploy/crds/policy.open-cluster-management.io_operatorpolicies.yaml

              make deploy

              E2E_TEST_ARGS="--focus=Custom --focus=messages" make e2e-test || true

              echo "success?"
              ls -lah
