apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: jkuli-mch-integration-test
spec:
  params:
    - description: 'Snapshot of the application'
      name: SNAPSHOT
      default: |
        {
          "application": "release-acm-211",
          "components": [{
            "name": "config-policy-controller-acm-211",
            "containerImage": "quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/config-policy-controller-acm-211@sha256:4a28d4e8f2409815a9abc691408d6f75afbee04064ea2524d6c06f12e65ec93e",
            "source": {
              "git": {
                "url": "https://github.com/stolostron/config-policy-controller",
                "revision": "1082f5e293acc33c656ae8d136d76f4c0f7eef89"
              }
            }
          }],
          "artifacts": {}
        }
      type: string
  tasks:
    - name: setup
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
      taskSpec:
        params:
          - name: SNAPSHOT
        results:
          - name: SKIP_NOTE
        volumes:
          - name: "jkuli-test-cm"
            configMap:
              name: "jkuli-test-cm"
        steps:
          - image: registry.redhat.io/openshift4/ose-cli:latest
            env:
              - name: SNAPSHOT
                value: $(params.SNAPSHOT)
              - name: OCP_API_URL
                valueFrom:
                  secretKeyRef:
                    name: jkuli-test-secret
                    key: api_url
              - name: OCP_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: jkuli-test-secret
                    key: password
            volumeMounts:
              - name: "jkuli-test-cm"
                mountPath: "/tmp/vol"
            script: |
              #!/usr/bin/env bash
              set -u # no "-e" or "-o pipefail", for now

              oc login "${OCP_API_URL}" -u kubeadmin -p "${OCP_PASSWORD}" --insecure-skip-tls-verify=true
              
              if (( $? != 0 )); then
                echo -n "Could not log in to cluster" | tee $(results.SKIP_NOTE.path)
                exit 0
              fi

              oc create -f - <<EOF
              apiVersion: coordination.k8s.io/v1
              kind: Lease
              metadata:
                name: konflux-integration-lock
                namespace: default
              EOF

              if (( $? != 0 )); then
                echo -n "The test cluster is already in use" | tee $(results.SKIP_NOTE.path)
                exit 0
              fi

              echo -n "" | tee $(results.SKIP_NOTE.path)

              set -eo pipefail

              echo "cloning multiclusterhub-operator repository"
              dnf -y install git
              git clone https://github.com/JustinKuli/multiclusterhub-operator.git
              cd multiclusterhub-operator/
              git checkout 2.11-integration-test
              
              cd hack/scripts
              ./integration-setup.sh

  finally:
    - name: finish-skip
      when:
        - input: $(tasks.setup.results.SKIP_NOTE)
          operator: notin
          values: [""]
      taskSpec:
        results:
          - name: TEST_OUTPUT
        steps:
          - image: registry.redhat.io/openshift4/ose-cli:latest
            script: |
              #!/usr/bin/env bash
              set -euo pipefail
              
              res='{"result": "SKIPPED", "timestamp": "'$(date -u --iso-8601=seconds)'", '
              res+='"successes": 0, "failures": 0, "warnings": 0, '
              res+='"note": "$(tasks.setup.results.SKIP_NOTE)"}'
              echo -n "${res}" | tee $(results.TEST_OUTPUT.path)
              echo ""
    - name: finish-cleanup
      when:
        - input: $(tasks.setup.results.SKIP_NOTE)
          operator: in
          values: [""]
      taskSpec:
        results:
          - name: TEST_OUTPUT
        steps:
          - image: registry.redhat.io/openshift4/ose-cli:latest
            env:
              - name: OCP_API_URL
                valueFrom:
                  secretKeyRef:
                    name: jkuli-test-secret
                    key: api_url
              - name: OCP_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: jkuli-test-secret
                    key: password
            script: |
              #!/usr/bin/env bash
              set -euo pipefail
              
              oc login "${OCP_API_URL}" -u kubeadmin -p "${OCP_PASSWORD}" --insecure-skip-tls-verify=true

              res='{"result": "SUCCESS", "timestamp": "'$(date -u --iso-8601=seconds)'", '
              res+='"successes": 0, "failures": 0, "warnings": 0, '
              res+='"note": "I'"'"'m making a note here: huge success"}'
              echo -n "${res}" | tee $(results.TEST_OUTPUT.path)
              echo ""

              oc delete lease -n default konflux-integration-lock
